import os
import uuid
import logging
from typing import List, Dict
from gtts import gTTS
from pptx import Presentation
from PIL import Image, ImageDraw
from app.core.config import AUDIO_DIR, SLIDES_DIR, VIDEO_DIR, BASE_DIR

logger = logging.getLogger(__name__)

# Conditional import for moviepy to handle environments where it might not be installed or needed immediately
try:
    from moviepy import ImageClip, AudioFileClip, concatenate_videoclips
except ImportError:
    ImageClip = None
    AudioFileClip = None
    concatenate_videoclips = None


def generate_audio_file(text: str, schema: str = "en") -> str:
    """Helper to generate an audio file from text using gTTS."""
    try:
        os.makedirs(AUDIO_DIR, exist_ok=True)
        filename = f"{uuid.uuid4()}.mp3"
        filepath = os.path.join(AUDIO_DIR, filename)
        
        tts = gTTS(text=text, lang=schema)
        tts.save(filepath)
        
        logger.info(f"Generated audio file: {filepath}")
        return os.path.relpath(filepath, BASE_DIR)
    except Exception as e:
        logger.error(f"Error generating audio: {e}")
        raise

def generate_audio_summary(text: str) -> str:
    """
    Generates an audio file reading the provided text.
    Use this to create a podcast-style summary or explanation for the user.
    
    Args:
        text: The text content to be spoken.
        
    Returns:
        The path to the generated audio file.
    """
    return generate_audio_file(text)

def generate_presentation_file(title: str, slides: List[Dict[str, str]]) -> str:
    """
    Generates a PowerPoint presentation file.
    
    Args:
        title: The title of the presentation.
        slides: A list of dictionaries, where each dict has a 'title' string and a 'content' string.
                Example: [{"title": "Intro", "content": "Hello World"}]
                
    Returns:
        The path to the generated .pptx file.
    """
    try:
        os.makedirs(SLIDES_DIR, exist_ok=True)
        
        prs = Presentation()
        
        # Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        slide.shapes.title.text = title
        slide.placeholders[1].text = "Generated by AI Research Assistant"
        
        # Content Slides
        bullet_slide_layout = prs.slide_layouts[1]
        
        for slide_data in slides:
            slide = prs.slides.add_slide(bullet_slide_layout)
            shapes = slide.shapes
            
            shapes.title.text = slide_data.get("title", "Untitled Slide")
            shapes.placeholders[1].text_frame.text = slide_data.get("content", "")
            
        filename = f"{uuid.uuid4()}.pptx"
        filepath = os.path.join(SLIDES_DIR, filename)
        prs.save(filepath)
        
        logger.info(f"Generated presentation: {filepath}")
        return os.path.relpath(filepath, BASE_DIR)
        
    except Exception as e:
        logger.error(f"Error generating presentation: {e}")
        return f"Error: {e}"

def create_slide_image(title: str, content: str, filename: str):
    """Creates a simple slide image using Pillow."""
    width = 1280
    height = 720
    background_color = (255, 255, 255)
    text_color = (0, 0, 0)
    
    img = Image.new('RGB', (width, height), color=background_color)
    d = ImageDraw.Draw(img)
    
    # Simple layout
    d.text((50, 50), title, fill=text_color)
    
    y_text = 150
    lines = content.split('\n')
    for line in lines:
        d.text((50, y_text), line, fill=text_color)
        y_text += 40
        
    img.save(filename)

def generate_video_lecture_file(title: str, slides: List[Dict[str, str]]) -> str:
    """
    Generates an MP4 video lecture.
    
    Args:
        title: The title of the lecture.
        slides: A list of dictionaries, where each dict has a 'title' string and a 'content' string.
                Content is spoken in the video and shown on the slide.
                Example: [{"title": "Concept A", "content": "Explanation of A..."}]
                
    Returns:
        The path to the generated .mp4 file.
    """
    if not ImageClip:
        return "Error: moviepy library not available."

    try:
        os.makedirs(VIDEO_DIR, exist_ok=True)
        clips = []
        
        # 1. Title Sequence
        title_img_path = os.path.join(VIDEO_DIR, f"{uuid.uuid4()}_title.png")
        create_slide_image(title, "AI Research Assistant Presentation", title_img_path)
        
        # Intro Audio
        intro_audio_path = generate_audio_file(f"Welcome to the lecture on {title}")
        
        audio_clip = AudioFileClip(intro_audio_path)
        img_clip = ImageClip(title_img_path).with_duration(audio_clip.duration)
        img_clip = img_clip.with_audio(audio_clip)
        clips.append(img_clip)
        
        # 2. Content Slides
        for slide in slides:
            slide_title = slide.get("title", "")
            slide_text = slide.get("content", "")
            
            # Image
            img_path = os.path.join(VIDEO_DIR, f"{uuid.uuid4()}_slide.png")
            create_slide_image(slide_title, slide_text, img_path)
            
            # Audio
            audio_path = generate_audio_file(slide_text)
            
            slide_audio = AudioFileClip(audio_path)
            slide_clip = ImageClip(img_path).with_duration(slide_audio.duration)
            slide_clip = slide_clip.with_audio(slide_audio)
            clips.append(slide_clip)
            
        # 3. Concatenate
        final_clip = concatenate_videoclips(clips)
        output_filename = f"{uuid.uuid4()}.mp4"
        output_path = os.path.join(VIDEO_DIR, output_filename)
        
        final_clip.write_videofile(output_path, fps=24, codec='libx264')
        
        logger.info(f"Generated video: {output_path}")
        return os.path.relpath(output_path, BASE_DIR)
        
    except Exception as e:
        logger.error(f"Error generating video: {e}")
        return f"Error: {e}"
