steps:
  # 1. Build the Docker image with build arguments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}'
      - '--build-arg'
      - 'VITE_FIREBASE_STORAGE_BUCKET=${_VITE_FIREBASE_STORAGE_BUCKET}'
      - '--build-arg'
      - 'VITE_FIREBASE_MESSAGING_SENDER_ID=${_VITE_FIREBASE_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'VITE_FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID}'
      - '--build-arg'
      - 'FIREBASE_DATABASE_ID=${_FIREBASE_DATABASE_ID}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
      - '.'

  # 2. Push the image to Artifact Registry / GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      # Pass the Database ID and Storage Bucket to the runtime environment
      - '--set-env-vars'
      - 'FIREBASE_DATABASE_ID=${_FIREBASE_DATABASE_ID}'
      - '--set-env-vars'
      - 'VITE_FIREBASE_STORAGE_BUCKET=${_VITE_FIREBASE_STORAGE_BUCKET}'
      - '--set-env-vars'
      - 'GCS_BUCKET_NAME=${_VITE_FIREBASE_STORAGE_BUCKET}'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'

substitutions:
  _SERVICE_NAME: 'aletheia-qa' # Default to qa if not specified
  _REGION: 'us-central1'
  _FIREBASE_DATABASE_ID: 'qa-research-db'
  _VITE_FIREBASE_API_KEY: ''
  _VITE_FIREBASE_AUTH_DOMAIN: ''
  _VITE_FIREBASE_PROJECT_ID: ''
  _VITE_FIREBASE_STORAGE_BUCKET: ''
  _VITE_FIREBASE_MESSAGING_SENDER_ID: ''
  _VITE_FIREBASE_APP_ID: ''

options:
  logging: CLOUD_LOGGING_ONLY
